### ISSUE TITLE
Measure unit test coverage and set up milestones for increasing it

### ISSUE THREAD

**Issue by jindrahelcl** [ufal/neuralmonkey#197]
There are modules (such as https://pypi.python.org/pypi/coverage), which allows to measure the code coverage. If run on unit test, one can measure the amount of code covered by the tests.

I propose to:

- [ ] Add the coverage measurement to Travis unit test scenario
- [ ] Set up an issue and milestone system for increasing unit test coverage
- [ ] Open a corresponding testing issue every time a pull request is merged and closed, maybe request a test case in every pull request solving a bug issue. I wouldn't require tests in all pull requests, since it might slow the development process too much.

**Comment by martinpopel** [comment]
I have seen people preferring https://coveralls.io/ instead of Travis for this purpose.

**Comment by nishnik** [comment]
@jindrahelcl You all are doing a terrific work here. Can I solve this issue, I could work on integrating coveralls.
