### ISSUE TITLE
Things that we need to refactor

### ISSUE THREAD

**Issue by tomasmcz** [ufal/neuralmonkey#9]
While I try to make #6 happen, I find many issues that I am not capable/willing to address. I will maintain a checklist of what needs to be done here. Btw. you would not believe how much code that clearly is not working (`random.random > 0.5`, unused variables, ...) I've encountered so far.
- [ ] `processors/bpe.py` classes are questionable here.
- [ ] `processors/german.py` classes are questionable
- [x] `utils.py` This needs to be a class!
- [x] `logging.py` various
- [ ] `decoding_function.py` There are lots of arguments, some unused. This needs a complete refactor.
- [ ] `mlp.py` This really should not be a class. Also, aren't there any implementations of multilayered perceptron that we can use?
- [ ] `readers/plain_text_reader.py` This should not be a class.
- [x] `config/config_loader.py` general exceptions, see #12 
- [x] `config/configuration.py` general exceptions, see #12
- [x] `config/config_generator.py` I think this should be abandoned, see #17 
- [ ] `encoders/sentence_encoder.py` crazy big object, 13 parameters...
- [ ] `encoders/image_encoder.py` dtto
- [ ] `encoders/cnn_encoder.py` dtto
- [ ] `bidirectional_rnn_layer.py` class is questionable
- [ ] `tokenize_data.py` oh the horror
- [ ] `decoders/sequence_classifier.py` too many instance attributes
- [x] `decders/decoder.py` big and ugly object
- [ ] `image_utils.py` questionable class
- [ ] `prepare_str_images.py` general exception
- [ ] `precompute_image_features.py` too long, break it up
- [ ] `trainers/copynet.py` undefined variable!
- [ ] `trainers/cross_entropy_trainer.py` questionable class
- [ ] `trainers/mixer.py` various errors
- [ ] `decompound_truecase.py` javabridge
- [ ] `runners/runner.py` questionable class
- [ ] `runners/beamsearch.py` questionable class
- [ ] `runners/copynet_runner.py` undefined variable!
- [ ] `runners/perplexity.py` questionable class
- [x] `logbook/logbook.py` dependencies
- [ ] `cells/noisy_gru_cells.py` various
- [ ] `learning_utils.py` pure evil – half-screen levels of indentation
- [ ] `caffe_image_features.py` imports and other things
- [x] `lazy_dataset.py` argument numbers, non-existent members
- [ ] `reformat_downloaded_image_features.py` imports

**Comment by jindrahelcl** [comment]
- `processors/bpe.py` have you look to `processors/README.md`? I am using this now and still working on it.
- `readers/plain_text_reader.py` why not? I turned this into a class for the case we will need a parser for a different type of file (e.g. NIST format that is used on WMT). Anyway, this refactoring is still not finished.

**Comment by tomasmcz** [comment]
- `processors/bpe.py` relative imports are confusing pylint, this should be resolved with #4 
- `readers/plain_text_reader.py` Class with just one public method should just be a function. Pylint rightfully complaints that there are “too few public methods”.

**Comment by jindrahelcl** [comment]
Speaking of `readers/plain_text_reader.py`, I don't understand the type annotations. I get why you added the `() ->`, but I have no idea why have you changed `Generator` to `Iterator`... Iterator is an object that has the `__iter__` method. Generator is built implicitly by the `yield` statement. Do you have any grounds for this change?

https://www.python.org/dev/peps/pep-0484/#annotating-generator-functions-and-coroutines
http://stackoverflow.com/questions/2776829/difference-between-pythons-generators-and-iterators
http://stackoverflow.com/questions/27264250/how-to-annotate-a-generator-in-python3

**Comment by jindrahelcl** [comment]
@tomasmcz ?

**Comment by tomasmcz** [comment]
The iterator thing was just an experiment that I commited by mistake. Before doing anything serious with type annotations, we should decide whether to move to Python 3 (#3).

**Comment by tomasmcz** [comment]
The list should now be complete. I fixed everything I could, the rest for someone who understands the code. Will anybody work on this or should I just continuously open new issues to discuss what to do with each file?

**Comment by jindrahelcl** [comment]
keep it here. i will do some.

**Comment by jindrahelcl** [comment]
utils.py refactored and renamed to logging.py with a class with static methods and exporting symbols `log` and `log_print` for easier access to the in-class logging functions.

**Comment by jindrahelcl** [comment]
As for the questionable classes, i don't see much point in investing time to change these. It works in the same way as if they were functions but now they are not required to return millions of values. I can add '@property' functions to these classes, but anything else is a bad idea

**Comment by jlibovicky** [comment]
And does it print to file now?

**Comment by jindrahelcl** [comment]
Yeah, it seems it is (at least when you run the run_tests or the tests_run or whatever, it works).. I was just about to post it to #41

**Comment by tomasmcz** [comment]
I'm not saying that all the questionable classes should be refactored (that's why I put "questionable" there). We should decide whether they really should be classes and in case they should, we should communicate that decision with a comment that disables the pylint warning which is saying that they should not.

**Comment by jlibovicky** [comment]
I suggest closing this issue and create a new list eventually. Many of the problems persist, but many files have changed and the discussion above is not relevant any more.

**Comment by jindrahelcl** [comment]
hear hear
